# This is a basic workflow to help you get started with Actions

name: BuildPackages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install prerequisites
      run: apt -y install rpm fakeroot dpkg perl tar

    # Runs a set of commands using the runners shell
    - name: Execute builds
      run: ./Build.all
        
    - name: Upload builds
    uses: actions/upload-artifact@v2
    with:
      # Artifact name
      name: Builds
      # A file, directory or wildcard pattern that describes what to upload
      path: ~/msbuilds/*
